package httpapi

import "github.com/hobbyquaker/occulited/internal/apidoc"

// routeDocs is every route's summary for the API documents (openccu-lite task 298), keyed by the
// route table's pattern, and what the generator cannot read from the handler: the request or answer
// of a handler that does not use readJSON/writeJSON, a body that is not JSON, a stream. The scope is
// not repeated here - the documents take it from the table. A new route needs its line here
// (TestEveryRouteDocumented), and a changed handler a regenerated docs/openapi.json
// (TestAPIDocuments); docs/system-api.md and docs/meta-api.md stay the prose.
var routeDocs = map[string]apidoc.Doc{
	"GET /api/openapi.json": {Summary: "This document: the OpenAPI description of the running occulited", RespSchema: apidoc.Schema{"type": "object", "description": "An OpenAPI 3.1 document, info.version the running occulited's"}},

	// auth
	"GET /api/auth/v1/config":                        {Summary: "The session lifetimes and the login settings (OIDC, password login)"},
	"PUT /api/auth/v1/config":                        {Summary: "Changes the session lifetimes and the login settings"},
	"GET /api/auth/v1/confirm":                       {Summary: "How this session confirms a sensitive action: password, OIDC or none"},
	"POST /api/auth/v1/legacy-sid":                   {Summary: "The session's CCU-style `?sid=@…@` alias for addon pages"},
	"POST /api/auth/v1/login":                        {Summary: "Logs in with user name and password"},
	"POST /api/auth/v1/login/passkey":                {Summary: "Starts a sign-in with a passkey (no name, no password)"},
	"POST /api/auth/v1/login/passkey/finish":         {Summary: "Finishes a passkey sign-in and opens the session"},
	"POST /api/auth/v1/logout":                       {Summary: "Ends the sessions the request carries and deletes the cookies"},
	"GET /api/auth/v1/me/preferences":                {Summary: "The caller's own shell preferences"},
	"PUT /api/auth/v1/me/preferences":                {Summary: "Stores the caller's own shell preferences"},
	"GET /api/auth/v1/me/webauthn":                   {Summary: "The caller's passkeys"},
	"POST /api/auth/v1/me/webauthn/begin":            {Summary: "Starts registering a passkey on the caller's account (needs a confirmed ticket)"},
	"POST /api/auth/v1/me/webauthn/finish":           {Summary: "Finishes registering a passkey on the caller's account"},
	"DELETE /api/auth/v1/me/webauthn/{id}":           {Summary: "Removes one of the caller's passkeys (needs a confirmed ticket)"},
	"GET /api/auth/v1/oidc":                          {Summary: "Whether sign-in with an OIDC provider is offered, and its label"},
	"GET /api/auth/v1/oidc/callback":                 {Summary: "The OIDC provider's return: opens the session or issues the confirmation", Query: map[string]string{"code": "The authorization code", "state": "The flow's state", "error": "The provider's error code", "error_description": "The provider's error text"}},
	"GET /api/auth/v1/oidc/confirm":                  {Summary: "Confirms a sensitive action at the OIDC provider (a redirect)", Query: map[string]string{"path": "The API path the confirmed ticket is for", "return": "Where the browser goes afterwards"}},
	"POST /api/auth/v1/oidc/peer-chain":              {Summary: "Reads the identity provider's certificate chain, to pin or trust it"},
	"GET /api/auth/v1/oidc/start":                    {Summary: "Starts the OIDC sign-in (a redirect to the provider)", Query: map[string]string{"return": "Where the browser goes afterwards"}},
	"POST /api/auth/v1/oidc/test":                    {Summary: "Tests the OIDC settings against the provider"},
	"GET /api/auth/v1/oidc/trust":                    {Summary: "The certificates trusted for the identity provider"},
	"POST /api/auth/v1/oidc/trust":                   {Summary: "Adds a certificate trusted for the identity provider"},
	"DELETE /api/auth/v1/oidc/trust/{id}":            {Summary: "Removes a certificate trusted for the identity provider"},
	"GET /api/auth/v1/pairing":                       {Summary: "Client pairing: the switch and the open requests"},
	"POST /api/auth/v1/pairing/request":              {Summary: "Client pairing: a program asks for access (no session; the answer's secret polls)"},
	"DELETE /api/auth/v1/pairing/request/{id}":       {Summary: "Client pairing: the program withdraws its request"},
	"GET /api/auth/v1/pairing/request/{id}":          {Summary: "Client pairing: the program polls its request; approved, the answer carries the token once"},
	"PUT /api/auth/v1/pairing/settings":              {Summary: "Client pairing: switches it on or off"},
	"GET /api/auth/v1/pairing/stream":                {Summary: "Client pairing: the requests as server-sent events"},
	"POST /api/auth/v1/pairing/{id}/approve":         {Summary: "Client pairing: approves a request with the scopes chosen"},
	"POST /api/auth/v1/pairing/{id}/reject":          {Summary: "Client pairing: rejects a request"},
	"POST /api/auth/v1/password":                     {Summary: "Changes the caller's password, or an administrator resets another account's"},
	"DELETE /api/auth/v1/sessions":                   {Summary: "Ends every session of the caller's account (log out everywhere)"},
	"GET /api/auth/v1/sessions":                      {Summary: "The caller's sessions, or with `all=true` every account's (auth:admin)", Query: map[string]string{"all": "`true` lists every account's sessions (auth:admin)"}},
	"DELETE /api/auth/v1/sessions/{sid}":             {Summary: "Ends one session by its handle"},
	"POST /api/auth/v1/setup":                        {Summary: "Creates the first administrator on a fresh system and logs in"},
	"GET /api/auth/v1/state":                         {Summary: "Whether setup is needed, and who the caller is"},
	"POST /api/auth/v1/ticket":                       {Summary: "A one-time ticket for one GET of an API path (downloads, confirmations)"},
	"POST /api/auth/v1/ticket/redeem":                {Summary: "Turns a session ticket into a session of its own"},
	"GET /api/auth/v1/tokens":                        {Summary: "The API tokens and the scopes a token can have"},
	"POST /api/auth/v1/tokens":                       {Summary: "Creates an API token; the answer carries its secret once"},
	"POST /api/auth/v1/tokens/self/rotate":           {Summary: "A token replaces itself with a new secret"},
	"DELETE /api/auth/v1/tokens/{name}":              {Summary: "Deletes an API token"},
	"PATCH /api/auth/v1/tokens/{name}":               {Summary: "Renames a paired program's token label or narrows its scopes"},
	"GET /api/auth/v1/users":                         {Summary: "The accounts"},
	"POST /api/auth/v1/users":                        {Summary: "Creates an account"},
	"DELETE /api/auth/v1/users/{name}":               {Summary: "Deletes an account"},
	"PATCH /api/auth/v1/users/{name}":                {Summary: "Changes an account's level"},
	"GET /api/auth/v1/users/{name}/webauthn":         {Summary: "Another account's passkeys"},
	"DELETE /api/auth/v1/users/{name}/webauthn/{id}": {Summary: "Removes another account's passkey and ends its sessions"},
	"GET /api/auth/v1/webauthn":                      {Summary: "Whether any account has a passkey or any key, and the name keys are made on"},
	"POST /api/homematic.cgi":                        {Summary: "hmipserver's session check, answered for the loopback only", ReqContent: "application/json"},

	// meta
	"GET /api/meta/v1/enums":                           {Summary: "Every enum (room, function, …) with its full tree"},
	"POST /api/meta/v1/enums":                          {Summary: "Creates an enum"},
	"DELETE /api/meta/v1/enums/{enum}":                 {Summary: "Deletes an enum and its nodes"},
	"PATCH /api/meta/v1/enums/{enum}":                  {Summary: "Renames an enum"},
	"POST /api/meta/v1/enums/{enum}/nodes":             {Summary: "Creates a node in an enum's tree"},
	"DELETE /api/meta/v1/enums/{enum}/nodes/{path...}": {Summary: "Deletes a node and its subtree"},
	"PATCH /api/meta/v1/enums/{enum}/nodes/{path...}":  {Summary: "Renames, moves or reorders a node"},
	"GET /api/meta/v1/enums/{enum}/tree":               {Summary: "An enum's ordered tree"},
	"GET /api/meta/v1/events/sse":                      {Summary: "The metadata changes as server-sent events"},
	"GET /api/meta/v1/export":                          {Summary: "The whole metadata document, as JSON or YAML (`format=yaml`)", Resp: "github.com/hobbyquaker/occulited/internal/meta.Document"},
	"PUT /api/meta/v1/import":                          {Summary: "Replaces or merges the whole metadata document (JSON or YAML)", ReqContent: "application/json"},
	"POST /api/meta/v1/import/ccu":                     {Summary: "Imports names and rooms from a CCU's ReGa over the network"},
	"POST /api/meta/v1/import/regadom":                 {Summary: "Imports names and rooms from a ReGa database file"},
	"GET /api/meta/v1/objects":                         {Summary: "Every object, or those in an enum's subtree", Query: map[string]string{"enum": "An enum path: only the objects in that node's subtree", "orphaned": "`true` or `false`: only the orphaned objects, or none of them"}},
	"DELETE /api/meta/v1/objects/{ref}":                {Summary: "Forgets an object"},
	"GET /api/meta/v1/objects/{ref}":                   {Summary: "One object"},
	"PATCH /api/meta/v1/objects/{ref}":                 {Summary: "Creates or updates an object; `meta` merges per namespace"},
	"PUT /api/meta/v1/objects/{ref}":                   {Summary: "Creates or replaces an object"},
	"POST /api/meta/v1/objects:bulk":                   {Summary: "Sets and deletes many objects as one revision"},
	"GET /api/meta/v1/snapshot":                        {Summary: "The whole metadata store at one revision"},
	"GET /api/meta/v1/version":                         {Summary: "The API's version, the format, the revision and the server's capabilities"},

	// rpc
	"GET /api/rpc/v1/events":              {Summary: "lite-rpc: the interface processes' events as server-sent events", Stream: true, Query: map[string]string{"interface": "Only these interfaces (comma-separated or repeated)", "address": "Only these device or channel addresses", "key": "Only these datapoints (parameter names)", "datapoint": "An alias of key", "type": "Only these message types (event, state, interface, newDevices, …)"}},
	"GET /api/rpc/v1/events/ws":           {Summary: "lite-rpc: the same event stream over a WebSocket", WebSocket: true, Query: map[string]string{"interface": "Only these interfaces (comma-separated or repeated)", "address": "Only these device or channel addresses", "key": "Only these datapoints (parameter names)", "datapoint": "An alias of key", "type": "Only these message types (event, state, interface, newDevices, …)"}},
	"GET /api/rpc/v1/history":             {Summary: "lite-rpc: a datapoint's recorded history, or the list of recorded datapoints"},
	"GET /api/rpc/v1/interfaces":          {Summary: "lite-rpc: the interface processes this system runs"},
	"POST /api/rpc/v1/json/{interface}":   {Summary: "lite-rpc: one JSON-RPC 2.0 call or a batch to an interface process; each method needs its tier's scope", Req: "github.com/hobbyquaker/occulited/internal/literpc.jsonRequest", Resp: "github.com/hobbyquaker/occulited/internal/literpc.jsonResponse", Description: "A batch is an array of requests and answers an array. The methods and the scope each needs are in docs/lite-rpc-methods.json; `init` is refused. A browser session needs the credential in the Authorization header as well."},
	"GET /api/rpc/v1/state":               {Summary: "lite-rpc: the datapoints' last values from the state store"},
	"GET /api/rpc/v1/streams":             {Summary: "lite-rpc: the open event streams and their limits"},
	"DELETE /api/rpc/v1/streams/{id}":     {Summary: "lite-rpc: ends one event stream"},
	"POST /api/rpc/v1/xmlrpc/{interface}": {Summary: "lite-rpc: one XML-RPC call to an interface process; each method needs its tier's scope", ReqContent: "text/xml", RespContent: "text/xml", Description: "The methods and the scope each needs are in docs/lite-rpc-methods.json; `init` is refused, and a system.multicall is checked per inner call."},

	// system
	"POST /api/system/v1/addonctl":                                       {Summary: "An addon's own start/stop/restart request, with its addon token"},
	"GET /api/system/v1/addons":                                          {Summary: "The installed addons"},
	"GET /api/system/v1/addons/install":                                  {Summary: "The state of the running addon install job"},
	"GET /api/system/v1/addons/stream":                                   {Summary: "The addons' revision as server-sent events"},
	"POST /api/system/v1/addons/install":                                 {Summary: "Installs an addon archive (multipart `file` or a raw .tar.gz)", ReqContent: "application/octet-stream"},
	"POST /api/system/v1/addons/install/local":                           {Summary: "The firmware's install_addon hands an archive over, with its install token", ReqContent: "application/octet-stream"},
	"GET /api/system/v1/addons/updates":                                  {Summary: "The addon update check's results"},
	"POST /api/system/v1/addons/updates/check":                           {Summary: "Runs the addon update check now"},
	"POST /api/system/v1/addons/{id}/disable":                            {Summary: "Disables an addon (it no longer starts)"},
	"PUT /api/system/v1/addons/{id}/early-start":                         {Summary: "Switches an addon's early start"},
	"POST /api/system/v1/addons/{id}/enable":                             {Summary: "Enables an addon"},
	"PUT /api/system/v1/addons/{id}/legacy-session":                      {Summary: "Switches the legacy session for an addon"},
	"POST /api/system/v1/addons/{id}/ownership":                          {Summary: "Gives a confined addon its directories"},
	"GET /api/system/v1/addons/{id}/policy":                              {Summary: "An addon's confinement policy"},
	"PUT /api/system/v1/addons/{id}/policy":                              {Summary: "Sets an addon's confinement policy"},
	"POST /api/system/v1/addons/{id}/reinstall-dismiss":                  {Summary: "Hides an addon's reinstall hint at its current version"},
	"POST /api/system/v1/addons/{id}/uninstall":                          {Summary: "Uninstalls an addon"},
	"GET /api/system/v1/addons/{id}/update":                              {Summary: "Checks one addon for an update"},
	"GET /api/system/v1/addons/{id}/images/{kind}":                       {Summary: "An installed addon's icon or logo (kind: icon, icon-dark, logo, logo-dark), from its tree, as an image with a Content-Security-Policy", RespContent: "image/*"},
	"GET /api/system/v1/backup":                                          {Summary: "Creates a backup and downloads it (.sbk, or .sbk.age when encrypted)", RespContent: "application/octet-stream"},
	"GET /api/system/v1/backup/encryption":                               {Summary: "The backup encryption's switch and recovery key"},
	"PUT /api/system/v1/backup/encryption":                               {Summary: "Switches the backup encryption"},
	"POST /api/system/v1/backup/encryption/confirm":                      {Summary: "Confirms a new recovery key once the user stored it"},
	"POST /api/system/v1/backup/encryption/recovery":                     {Summary: "Starts setting up or rotating the recovery key"},
	"POST /api/system/v1/backup/encryption/test":                         {Summary: "Tests a recovery key against the one set up"},
	"PUT /api/system/v1/backup/nightly":                                  {Summary: "Switches the nightly backup and sets its time"},
	"POST /api/system/v1/backup/run":                                     {Summary: "Backs up to the default target now"},
	"GET /api/system/v1/backup/schedule":                                 {Summary: "The firmware's nightly backup schedule"},
	"PUT /api/system/v1/backup/schedule":                                 {Summary: "Sets the firmware's nightly backup schedule"},
	"POST /api/system/v1/backup/schedule/run":                            {Summary: "Runs the nightly backup now"},
	"GET /api/system/v1/backup/targets":                                  {Summary: "The backup targets and the nightly run"},
	"POST /api/system/v1/backup/targets":                                 {Summary: "Creates a backup target"},
	"DELETE /api/system/v1/backup/targets/{id}":                          {Summary: "Removes a backup target"},
	"PUT /api/system/v1/backup/targets/{id}":                             {Summary: "Changes a backup target"},
	"GET /api/system/v1/backup/targets/{id}/backups":                     {Summary: "The backups stored on a target"},
	"GET /api/system/v1/backup/targets/{id}/hostkey":                     {Summary: "An SFTP target's host key as the server shows it"},
	"PUT /api/system/v1/backup/targets/{id}/hostkey":                     {Summary: "Trusts an SFTP target's host key"},
	"POST /api/system/v1/backup/targets/{id}/keypair":                    {Summary: "Makes a new SSH key pair for an SFTP target"},
	"POST /api/system/v1/backup/targets/{id}/mount":                      {Summary: "Mounts an NFS or SMB target"},
	"POST /api/system/v1/backup/targets/{id}/run":                        {Summary: "Backs up to a target now"},
	"POST /api/system/v1/backup/targets/{id}/test":                       {Summary: "Tests writing to a target"},
	"POST /api/system/v1/backup/targets/{id}/unmount":                    {Summary: "Unmounts an NFS or SMB target"},
	"GET /api/system/v1/boot":                                            {Summary: "The boot timeline of one boot"},
	"GET /api/system/v1/boot-expect":                                     {Summary: "How long a reboot of a kind is expected to take"},
	"POST /api/system/v1/boot-timing":                                    {Summary: "Records what the page observed during a reboot"},
	"GET /api/system/v1/boots":                                           {Summary: "The boots the journal holds"},
	"GET /api/system/v1/catalog":                                         {Summary: "The addon catalogue and the installed addons' releases"},
	"GET /api/system/v1/catalog/progress":                                {Summary: "The progress of a catalogue install"},
	"POST /api/system/v1/catalog/refresh":                                {Summary: "Checks the addon catalogue now"},
	"PUT /api/system/v1/catalog/settings":                                {Summary: "Switches the catalogue's daily check"},
	"POST /api/system/v1/catalog/{id}/install":                           {Summary: "Installs or updates an addon from the catalogue"},
	"GET /api/system/v1/catalog/{id}/images/{kind}":                      {Summary: "A catalogue entry's icon or logo (kind: icon, icon-dark, logo, logo-dark), fetched with its manifest, as an image with a Content-Security-Policy", RespContent: "image/*"},
	"GET /api/system/v1/certificate":                                     {Summary: "The certificate: settings, the current one and the issued one"},
	"GET /api/system/v1/certificate/csr":                                 {Summary: "Downloads the pending certificate signing request", RespContent: "application/pkcs10"},
	"POST /api/system/v1/certificate/inspect":                            {Summary: "Parses a certificate or chain for the preview"},
	"POST /api/system/v1/certificate/issue":                              {Summary: "Issues a certificate through ACME"},
	"POST /api/system/v1/certificate/key":                                {Summary: "Makes a new key and signing request"},
	"PUT /api/system/v1/certificate/manual":                              {Summary: "Sets the user's own certificate and key"},
	"POST /api/system/v1/certificate/renew":                              {Summary: "Renews the ACME certificate now"},
	"POST /api/system/v1/certificate/self-signed":                        {Summary: "Goes back to a self-signed certificate"},
	"PUT /api/system/v1/certificate/settings":                            {Summary: "Changes the certificate settings (ACME, names)"},
	"POST /api/system/v1/certificate/test":                               {Summary: "Runs the ACME flow against the staging server"},
	"GET /api/system/v1/datastore":                                       {Summary: "occulited's database file: its place and size"},
	"PUT /api/system/v1/datastore":                                       {Summary: "Moves occulited's database file"},
	"GET /api/system/v1/datastore/history":                               {Summary: "The datapoint history's settings and list"},
	"PUT /api/system/v1/datastore/history":                               {Summary: "Changes the datapoint history's settings and list"},
	"GET /api/system/v1/early-start":                                     {Summary: "The early addon start's switches"},
	"PUT /api/system/v1/early-start":                                     {Summary: "Sets the early addon start's switches"},
	"DELETE /api/system/v1/factory-reset":                                {Summary: "Cancels an armed factory reset"},
	"GET /api/system/v1/factory-reset":                                   {Summary: "What a factory reset would remove, and whether one is armed"},
	"POST /api/system/v1/factory-reset":                                  {Summary: "Arms a factory reset for the next boot and reboots"},
	"GET /api/system/v1/firewall":                                        {Summary: "The firewall: the live rules and the draft"},
	"PUT /api/system/v1/firewall":                                        {Summary: "Sets the firewall draft"},
	"GET /api/system/v1/firewall/addons":                                 {Summary: "The addons' firewall port switches"},
	"PUT /api/system/v1/firewall/addons/{id}/ports":                      {Summary: "Opens or closes an addon's ports"},
	"POST /api/system/v1/firewall/apply":                                 {Summary: "Applies the draft for 60 seconds, reverting unless confirmed"},
	"POST /api/system/v1/firewall/confirm":                               {Summary: "Keeps the applied firewall"},
	"GET /api/system/v1/firewall/counters":                               {Summary: "The firewall rules' packet and byte counters"},
	"POST /api/system/v1/firewall/counters/reset":                        {Summary: "Resets the firewall counters"},
	"DELETE /api/system/v1/firewall/draft":                               {Summary: "Discards the firewall draft"},
	"GET /api/system/v1/firewall/listeners":                              {Summary: "The ports the system listens on"},
	"POST /api/system/v1/firewall/migration/dismiss":                     {Summary: "Hides the firewall migration notice"},
	"POST /api/system/v1/firewall/revert":                                {Summary: "Reverts the applied firewall now"},
	"GET /api/system/v1/firmware":                                        {Summary: "Device firmware: the modules, files and the check's state"},
	"GET /api/system/v1/firmware/bundles/{type_code}/files/{name}":       {Summary: "One text file of a device firmware bundle"},
	"POST /api/system/v1/firmware/check":                                 {Summary: "Checks for device firmware now"},
	"PUT /api/system/v1/firmware/settings":                               {Summary: "Switches the device firmware check"},
	"POST /api/system/v1/firmware/upload":                                {Summary: "Uploads a device firmware file", ReqContent: "application/octet-stream"},
	"GET /api/system/v1/groups":                                          {Summary: "The heating groups"},
	"POST /api/system/v1/groups":                                         {Summary: "Creates a heating group"},
	"GET /api/system/v1/groups/types":                                    {Summary: "The heating group types and the devices they can hold"},
	"DELETE /api/system/v1/groups/{id}":                                  {Summary: "Deletes a heating group"},
	"GET /api/system/v1/groups/{id}":                                     {Summary: "One heating group"},
	"PUT /api/system/v1/groups/{id}":                                     {Summary: "Changes a heating group"},
	"POST /api/system/v1/halt":                                           {Summary: "Shuts the system down"},
	"GET /api/system/v1/https":                                           {Summary: "The HTTPS redirect and HSTS settings"},
	"PUT /api/system/v1/https":                                           {Summary: "Sets the HTTPS redirect and HSTS"},
	"GET /api/system/v1/journal":                                         {Summary: "The journal's storage mode and settings"},
	"PUT /api/system/v1/journal":                                         {Summary: "Sets the journal's storage mode"},
	"POST /api/system/v1/journal/sync":                                   {Summary: "Copies the RAM journal to the userfs now"},
	"GET /api/system/v1/led":                                             {Summary: "The status LED's configuration"},
	"PUT /api/system/v1/led":                                             {Summary: "Sets the status LED's configuration"},
	"DELETE /api/system/v1/led/locate":                                   {Summary: "Stops the status LED's locate blink"},
	"POST /api/system/v1/led/locate":                                     {Summary: "Blinks the status LED to find the system"},
	"DELETE /api/system/v1/led/override":                                 {Summary: "Ends the caller's own status LED override"},
	"POST /api/system/v1/led/override":                                   {Summary: "Sets a status LED override (color, pattern, duration)"},
	"DELETE /api/system/v1/led/override/{id}":                            {Summary: "Ends one status LED override"},
	"DELETE /api/system/v1/led/overrides":                                {Summary: "Ends every status LED override"},
	"DELETE /api/system/v1/led/preview":                                  {Summary: "Ends the status LED preview"},
	"POST /api/system/v1/led/preview":                                    {Summary: "Previews a status LED color and pattern for 10 seconds"},
	"GET /api/system/v1/led/state":                                       {Summary: "What the status LED shows now, and why"},
	"GET /api/system/v1/leds":                                            {Summary: "The onboard LEDs' switch"},
	"PUT /api/system/v1/leds":                                            {Summary: "Switches the onboard LEDs"},
	"GET /api/system/v1/legacy-session":                                  {Summary: "The legacy session's switches"},
	"PUT /api/system/v1/legacy-session":                                  {Summary: "Sets the legacy session's switches"},
	"GET /api/system/v1/log":                                             {Summary: "The journal, filtered"},
	"GET /api/system/v1/log/download":                                    {Summary: "Downloads the journal, filtered", RespContent: "application/octet-stream"},
	"GET /api/system/v1/log/stream":                                      {Summary: "The journal as server-sent events"},
	"GET /api/system/v1/loglevels":                                       {Summary: "The log levels of the interface processes, lighttpd and occulited"},
	"PUT /api/system/v1/loglevels":                                       {Summary: "Sets the log levels"},
	"GET /api/system/v1/nav":                                             {Summary: "The shell's menu entries (addon pages included)"},
	"GET /api/system/v1/network":                                         {Summary: "The network settings and the pending change"},
	"POST /api/system/v1/network":                                        {Summary: "Applies a network change, reverting unless confirmed"},
	"POST /api/system/v1/network/confirm":                                {Summary: "Keeps the network change"},
	"GET /api/system/v1/network/ipv6":                                    {Summary: "IPv6 per interface"},
	"POST /api/system/v1/network/ipv6":                                   {Summary: "Applies an IPv6 change, reverting unless confirmed"},
	"POST /api/system/v1/network/ipv6/confirm":                           {Summary: "Keeps the IPv6 change"},
	"POST /api/system/v1/network/ipv6/revert":                            {Summary: "Reverts the IPv6 change now"},
	"GET /api/system/v1/network/pending":                                 {Summary: "The open network change, or null"},
	"POST /api/system/v1/network/revert":                                 {Summary: "Reverts the network change now"},
	"GET /api/system/v1/radio":                                           {Summary: "The radio inventory: modules, interfaces and mode"},
	"GET /api/system/v1/radio/connections":                               {Summary: "How each interface process connects to its radio"},
	"PUT /api/system/v1/radio/connections":                               {Summary: "Sets the radio connections and restarts the stack"},
	"POST /api/system/v1/radio/connections/preview":                      {Summary: "What a radio connection change would do"},
	"GET /api/system/v1/radio/device-descriptions":                       {Summary: "rfd's device description files"},
	"POST /api/system/v1/radio/device-descriptions/reset":                {Summary: "Restores the image's device description files"},
	"GET /api/system/v1/radio/firmware":                                  {Summary: "The radio modules' firmware files"},
	"POST /api/system/v1/radio/firmware/flash":                           {Summary: "Flashes a radio module's firmware"},
	"POST /api/system/v1/radio/firmware/upload":                          {Summary: "Uploads a radio module firmware file", ReqContent: "application/octet-stream"},
	"DELETE /api/system/v1/radio/firmware/{module}/{name}":               {Summary: "Removes an uploaded radio firmware file"},
	"GET /api/system/v1/radio/hb-rf-eth":                                 {Summary: "The network radio board (HB-RF-ETH) setting"},
	"PUT /api/system/v1/radio/hb-rf-eth":                                 {Summary: "Sets the network radio board (HB-RF-ETH)"},
	"POST /api/system/v1/radio/hb-rf-eth/find":                           {Summary: "Searches the network for HB-RF-ETH boards"},
	"GET /api/system/v1/radio/health":                                    {Summary: "The radio modules' health from the interface processes"},
	"GET /api/system/v1/radio/hmip/access-points":                        {Summary: "The HmIP access points paired to HmIP-RF"},
	"GET /api/system/v1/radio/hmip/device-keys":                          {Summary: "The HmIP device keys the system keeps"},
	"POST /api/system/v1/radio/hmip/device-keys":                         {Summary: "Adds an HmIP device key (from its QR code)"},
	"POST /api/system/v1/radio/hmip/device-keys/apply":                   {Summary: "Restarts HmIP-RF to take the device keys"},
	"GET /api/system/v1/radio/hmip/device-keys/export":                   {Summary: "The HmIP device keys as a key sheet (needs a confirmed ticket)"},
	"DELETE /api/system/v1/radio/hmip/device-keys/{sgtin}":               {Summary: "Removes an HmIP device key"},
	"GET /api/system/v1/radio/hmip/exchange":                             {Summary: "The HmIP adapter exchange's state"},
	"POST /api/system/v1/radio/hmip/exchange/fresh-start":                {Summary: "Starts afresh after a failed adapter exchange"},
	"POST /api/system/v1/radio/hmip/exchange/retry":                      {Summary: "Retries the adapter exchange"},
	"POST /api/system/v1/radio/hmip/module-move/back":                    {Summary: "Takes HmIP-RF back to the previous module from the snapshot"},
	"DELETE /api/system/v1/radio/hmip/local-key":                         {Summary: "Goes back to eQ-3's key server"},
	"GET /api/system/v1/radio/hmip/local-key":                            {Summary: "The HmIP local key mode's state"},
	"PUT /api/system/v1/radio/hmip/local-key":                            {Summary: "Switches to the HmIP local key mode"},
	"POST /api/system/v1/radio/hmip/local-key/override":                  {Summary: "Uses the key server for the next start once"},
	"DELETE /api/system/v1/radio/hmip/local-key/snapshots/{sgtin}":       {Summary: "Removes one module's key snapshot"},
	"POST /api/system/v1/radio/hmip/local-key/snapshots/{sgtin}/restore": {Summary: "Puts a previous module's identity back after a fresh start"},
	"DELETE /api/system/v1/radio/import":                                 {Summary: "Removes the device import record"},
	"GET /api/system/v1/radio/import":                                    {Summary: "The last device import and how it stands"},
	"POST /api/system/v1/radio/import/retry":                             {Summary: "Retries the device import"},
	"GET /api/system/v1/radio/lan-devices":                               {Summary: "eQ-3's LAN devices found on the network"},
	"POST /api/system/v1/radio/lan-devices/search":                       {Summary: "Searches for eQ-3's LAN devices"},
	"POST /api/system/v1/radio/lan-devices/{serial}/network":             {Summary: "Sets a LAN device's network"},
	"GET /api/system/v1/radio/lan-gateways":                              {Summary: "The LAN gateways configured"},
	"PUT /api/system/v1/radio/lan-gateways":                              {Summary: "Sets the LAN gateways"},
	"POST /api/system/v1/radio/lan-gateways/key":                         {Summary: "Sets a LAN gateway's key"},
	"POST /api/system/v1/radio/restart":                                  {Summary: "Restarts the radio stack in order"},
	"POST /api/system/v1/radio/security-key":                             {Summary: "Sets the system security key for BidCos"},
	"POST /api/system/v1/radio/subscribers/drop":                         {Summary: "Ends an interface process's hold on a stalled callback listener"},
	"GET /api/system/v1/radio/subscribers/reachability":                  {Summary: "Whether the interface processes' subscribers are reachable"},
	"POST /api/system/v1/radio/subscribers/remove":                       {Summary: "Removes a subscriber from an interface process"},
	"GET /api/system/v1/radio/subscribers/stalls":                        {Summary: "The interface processes held by a stalled callback listener"},
	"POST /api/system/v1/reboot":                                         {Summary: "Reboots the system"},
	"POST /api/system/v1/reboot/recovery":                                {Summary: "Reboots into the recovery system"},
	"GET /api/system/v1/remote-access":                                   {Summary: "The classic CCU RPC ports and their access"},
	"PUT /api/system/v1/remote-access":                                   {Summary: "Sets the classic CCU RPC ports and their access"},
	"PUT /api/system/v1/remote-access/classic-password":                  {Summary: "Sets the classic RPC password"},
	"POST /api/system/v1/restore/apply":                                  {Summary: "Restores a checked backup and reboots"},
	"POST /api/system/v1/restore/check":                                  {Summary: "Uploads a backup and checks it", ReqContent: "application/octet-stream"},
	"POST /api/system/v1/restore/decrypt":                                {Summary: "Decrypts an uploaded encrypted backup with the recovery key"},
	"GET /api/system/v1/restore/devices":                                 {Summary: "What a checked backup holds of the radio devices"},
	"POST /api/system/v1/restore/import-devices":                         {Summary: "Imports the radio devices from a backup"},
	"POST /api/system/v1/restore/verify-key":                             {Summary: "Checks a backup's passphrase"},
	"GET /api/system/v1/rpc-trace":                                       {Summary: "The lite-rpc trace's switch"},
	"PUT /api/system/v1/rpc-trace":                                       {Summary: "Sets the lite-rpc trace's switch"},
	"GET /api/system/v1/sbom":                                            {Summary: "The image's software bill of materials (CycloneDX)"},
	"GET /api/system/v1/service-messages":                                {Summary: "The service messages the system collects"},
	"GET /api/system/v1/service-messages/stream":                         {Summary: "The service messages as server-sent events"},
	"GET /api/system/v1/stream":                                          {Summary: "The shell's stream: addons, service messages and pairing requests as server-sent events"},
	"GET /api/system/v1/services":                                        {Summary: "The managed services and addon services, with their state"},
	"GET /api/system/v1/services/{id}/unit":                              {Summary: "A service's unit and its override"},
	"PUT /api/system/v1/services/{id}/unit":                              {Summary: "Sets a service's unit override"},
	"POST /api/system/v1/services/{id}/{action}":                         {Summary: "Starts, stops or restarts a service"},
	"GET /api/system/v1/ssh":                                             {Summary: "SSH: switched on, and whether sshd runs"},
	"PUT /api/system/v1/ssh":                                             {Summary: "Switches SSH"},
	"PUT /api/system/v1/ssh/key-only":                                    {Summary: "Allows only key login for root"},
	"DELETE /api/system/v1/ssh/keys":                                     {Summary: "Removes one of root's public keys"},
	"GET /api/system/v1/ssh/keys":                                        {Summary: "Root's public keys"},
	"POST /api/system/v1/ssh/keys":                                       {Summary: "Adds a public key for root"},
	"POST /api/system/v1/ssh/password":                                   {Summary: "Sets root's password"},
	"GET /api/system/v1/ssh/sessions":                                    {Summary: "The SSH connections open now"},
	"DELETE /api/system/v1/ssh/sessions/{id}":                            {Summary: "Ends an SSH connection"},
	"GET /api/system/v1/status":                                          {Summary: "The system's status: host, versions, uptime, memory, storage"},
	"GET /api/system/v1/storage":                                         {Summary: "The storage health: every disk, its facts and the verdict"},
	"GET /api/system/v1/storage/dirs":                                    {Summary: "Completes a folder name within a storage location"},
	"GET /api/system/v1/storage/locations":                               {Summary: "The places data can be kept (userfs, USB, shares)"},
	"GET /api/system/v1/storage/shares":                                  {Summary: "The network shares"},
	"POST /api/system/v1/storage/shares":                                 {Summary: "Creates a network share mount"},
	"DELETE /api/system/v1/storage/shares/{id}":                          {Summary: "Removes a network share mount"},
	"PUT /api/system/v1/storage/shares/{id}":                             {Summary: "Changes a network share mount"},
	"POST /api/system/v1/storage/shares/{id}/mount":                      {Summary: "Mounts a network share"},
	"POST /api/system/v1/storage/shares/{id}/test":                       {Summary: "Tests a network share"},
	"POST /api/system/v1/storage/shares/{id}/unmount":                    {Summary: "Unmounts a network share"},
	"GET /api/system/v1/storage/usb":                                     {Summary: "The USB disks and their partitions"},
	"POST /api/system/v1/storage/usb/{disk}/eject":                       {Summary: "Ejects a USB disk"},
	"POST /api/system/v1/storage/usb/{disk}/format":                      {Summary: "Formats a USB disk"},
	"DELETE /api/system/v1/system-update":                                {Summary: "Removes a staged system update"},
	"GET /api/system/v1/system-update":                                   {Summary: "The running version, the staged update and the release feed"},
	"POST /api/system/v1/addons/{id}/remove-rc-entry":                    {Summary: "Removes the rc.d entry of a script from the CCU"},
	"GET /api/system/v1/hmipserver/settings":                             {Summary: "hmipserver settings: whether the diagram data is kept"},
	"PUT /api/system/v1/hmipserver/settings":                             {Summary: "Switches hmipserver's diagram data"},
	"POST /api/system/v1/system-update/check":                            {Summary: "Asks the release feed now"},
	"POST /api/system/v1/system-update/download":                         {Summary: "Downloads the available release, or a named version"},
	"POST /api/system/v1/system-update/install":                          {Summary: "Installs the staged update (reboots into the recovery system)"},
	"GET /api/system/v1/system-update/releases":                          {Summary: "Lists this product's published releases in a channel"},
	"PUT /api/system/v1/system-update/settings":                          {Summary: "Switches the release feed's daily check"},
	"POST /api/system/v1/system-update/upload":                           {Summary: "Uploads a system update file", ReqContent: "application/octet-stream"},
	"GET /api/system/v1/time":                                            {Summary: "Time: the zone, NTP and the clock"},
	"PUT /api/system/v1/time":                                            {Summary: "Sets the time zone and NTP"},
	"POST /api/system/v1/time/clock":                                     {Summary: "Sets the clock by hand"},
	"GET /api/system/v1/time/zones":                                      {Summary: "The time zones"},
	"GET /api/system/v1/timers":                                          {Summary: "The systemd timers"},
	"POST /api/system/v1/timers/calendar":                                {Summary: "Checks and normalizes a systemd calendar expression"},
	"GET /api/system/v1/timers/own":                                      {Summary: "The user's own timers"},
	"POST /api/system/v1/timers/own":                                     {Summary: "Creates an own timer"},
	"DELETE /api/system/v1/timers/own/{name}":                            {Summary: "Deletes an own timer"},
	"GET /api/system/v1/timers/own/{name}":                               {Summary: "One own timer"},
	"PUT /api/system/v1/timers/own/{name}":                               {Summary: "Changes an own timer"},
	"POST /api/system/v1/timers/own/{name}/run":                          {Summary: "Runs an own timer's service once, now"},
	"GET /api/system/v1/trust":                                           {Summary: "The trust stores: the system's and the addons'"},
	"POST /api/system/v1/trust/{store}":                                  {Summary: "Adds a certificate to a trust store"},
	"DELETE /api/system/v1/trust/{store}/{id}":                           {Summary: "Removes or distrusts a certificate"},
	"POST /api/system/v1/trust/{store}/{id}/copy":                        {Summary: "Copies a certificate into another trust store"},
	"GET /api/system/v1/trust/{store}/{id}/pem":                          {Summary: "Downloads a certificate as PEM"},
	"POST /api/system/v1/trust/{store}/{id}/restore":                     {Summary: "Trusts a distrusted certificate again"},
	"POST /api/system/v1/trust/{store}/pins":                             {Summary: "Pins a public key for the OIDC or ACME connections"},
	"POST /api/system/v1/trust/{store}/pins/peer":                        {Summary: "Reads the chain the purpose's server presents, to pin one of its keys"},
	"DELETE /api/system/v1/trust/{store}/pins/{id}":                      {Summary: "Removes a pin"},
	"GET /api/system/v1/usb":                                             {Summary: "The USB devices"},
	"GET /api/system/v1/usb/storage":                                     {Summary: "The USB sticks mounted, for a directory backup target"},
	"GET /api/system/v1/warnings":                                        {Summary: "The Status page's warnings"},
	"POST /api/system/v1/warnings/silence":                               {Summary: "Silences a warning for some days"},
	"DELETE /api/system/v1/warnings/silence/{id}/{variant...}":           {Summary: "Ends a warning's silence"},
	"GET /api/system/v1/wifi":                                            {Summary: "Wi-Fi: the settings, the saved networks and the connection"},
	"PUT /api/system/v1/wifi":                                            {Summary: "Sets the Wi-Fi settings"},
	"POST /api/system/v1/wifi/confirm":                                   {Summary: "Keeps or reverts a change made over the Wi-Fi"},
	"POST /api/system/v1/wifi/networks":                                  {Summary: "Saves a Wi-Fi network and connects"},
	"DELETE /api/system/v1/wifi/networks/{ssid}":                         {Summary: "Forgets a saved Wi-Fi network"},
	"POST /api/system/v1/wifi/scan":                                      {Summary: "Scans for Wi-Fi networks"},
}

// extraDocs are routes outside the table: registered in main, open.
var extraDocs = map[string]apidoc.Doc{
	"GET /api/system/v1/health": {Summary: "Health check: the versions and the uptime, while occulited serves", RespSchema: apidoc.Schema{
		"type": "object", "required": []string{"ok", "version", "commit", "release", "base", "uptime_s", "meta"},
		"properties": apidoc.Schema{
			"ok": apidoc.Schema{"type": "boolean"}, "version": apidoc.Schema{"type": "string"}, "commit": apidoc.Schema{"type": "string"}, "release": apidoc.Schema{"type": "string"},
			"base": apidoc.Schema{"type": "string"}, "uptime_s": apidoc.Schema{"type": "integer"},
			"meta": apidoc.Schema{"type": "object", "required": []string{"revision", "recovered"}, "properties": apidoc.Schema{
				"revision": apidoc.Schema{"type": "integer"}, "recovered": apidoc.Schema{"type": "boolean"}}},
		}}},
}
